services:
  # Jellyfin - Media Server
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["media", "all"]
    networks:
      - default
    user: $PUID:$PGID
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    ports:
      - "$JELLYFIN_PORT:8096"
      # - "8920:8920" # Emby also uses same port if running both
    environment:
      UMASK_SET: 022
      TZ: $TZ
    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $DATADIR:/data
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    # labels:
    #   - homepage.group=Media
    #   - homepage.name=Jellyfin
    #   - homepage.href="http://192.168.1.11:8086"
      # - hompage.description="Media Server"
      # - homepage.widget.type=jellyfin
      # - homepage.widget.url="http://jellyfin:8096"
      # - homepage.widget.key="75ae47c2c40e4d588ba27d76c7dad291"